 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: alexnet-endpoint
 spec:
   replicas: 2
   selector:
     matchLabels:
       app: endpoint-app
   template:
     metadata:
       labels:
         app: endpoint-app
     spec:
       containers:
       - name: endpoint-app
         image: us.icr.io/imagenet/endpoint:alexnet
         imagePullPolicy: Always
         volumeMounts:
         - name: alexnet-pv
           mountPath: /mnt/data
         ports:
          - containerPort: 8002
       volumes:
       - name: alexnet-pv
         persistentVolumeClaim:
          claimName: alexnet-pvc